# Generated by Django 5.2.4 on 2025-07-24 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=5)),
                ('remarks', models.TextField(default='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('profile_pic', models.FileField(default='', upload_to='user_pic/')),
            ],
        ),
    ]
