# Generated by Django 5.2.4 on 2025-07-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0002_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAdvisor',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=70)),
                ('profile_pic', models.FileField(default='', upload_to='advisor_pic/')),
                ('experience', models.CharField(max_length=80)),
                ('skills', models.CharField(max_length=80)),
                ('service_type', models.CharField(max_length=50)),
            ],
        ),
    ]
