# Generated by Django 5.2.4 on 2025-07-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0003_legaladvisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
    ]
