# Generated by Django 5.2.4 on 2025-08-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0006_legalservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmService',
            fields=[
                ('service_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_description', models.TextField(default='')),
                ('service_pic', models.FileField(default='', upload_to='service_pic/')),
            ],
        ),
        migrations.DeleteModel(
            name='LegalService',
        ),
    ]
